jobs:
  publish-mew:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: cd packages/mew && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: cd packages/mew && npm publish --access public

workflows:
  mew:
    jobs:
      - publish-mew:
          filters:
            branches:
              only:
                - v2-web3-onboard
