jobs:
  publish-keepkey:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: cd packages/keepkey && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: cd packages/keepkey && npm publish --access public

workflows:
  keepkey:
    jobs:
      - publish-keepkey:
          filters:
            branches:
              only:
                - v2-web3-onboard
