jobs:
  check:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn setup
      - run: yarn build
      - run: cd packages/ledger && yarn lint
      - run: cd packages/ledger && yarn typescript
  publish:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn setup
      - run: yarn build
      - run: cd packages/ledger && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: cd packages/ledger && npm publish --access public

workflows:
  ledger:
    jobs:
      - check
      - publish:
          requires:
            - check
          filters:
            branches:
              only:
                - main
                - feature/v2
