jobs:
  check:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: pwd
      - run: echo $CIRCLE_WORKING_DIRECTORY
      - run: yarn lint
      - run: yarn check

workflows:
  core:
    jobs:
      - check
