jobs:
  publish-portis:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cd packages/portis && yarn build
      - run: cd packages/portis && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: cd packages/portis && npm publish --access public

workflows:
  portis:
    jobs:
      - publish-portis:
          filters:
            branches:
              only:
                - main
